print("Hello World!")
print("Hello Damir!")
print("Hello Burbach!")
print(" ")
print("Hello World!", end=" ")
print("Hello Damir!", end=" ")
print("Hello Burbach!")
print(" ")
print("Hello World!", end="*")
print("Hello Damir!", end="#")
print("Hello Burbach!")